when:
  - event: manual
  - event: pull_request
steps:
  check:
    image: rust
    commands:
      - cargo check
  check-fmt:
    image: rust
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
