when:
  - event: tag
steps:
  compile-linux:
    image: rust:latest
    environment:
      BUILD_TYPE: "release ci"
    commands:
      - rustup target add x86_64-unknown-linux-gnu
      - cargo build --target=x86_64-unknown-linux-gnu --release --features update-check
      - strip target/x86_64-unknown-linux-gnu/release/fj
  compile-windows:
    image: rust:latest
    environment:
      BUILD_TYPE: "release ci"
    commands:
      - rustup target add x86_64-pc-windows-gnu
      - apt update
      - apt install gcc-mingw-w64-x86-64 -y
      - cargo build --target=x86_64-pc-windows-gnu --release --features update-check
      - strip target/x86_64-pc-windows-gnu/release/fj.exe
  create-archives:
    image: code.cartoon-aa.xyz/ci/alpine-zip:3.22
    commands:
      - cd target/x86_64-pc-windows-gnu/release
      - zip ../../../forgejo-cli-x86_64-windows.zip fj.exe
      - cd ../../..
      - tar -czf forgejo-cli-x86_64-linux.tar.gz -C target/x86_64-unknown-linux-gnu/release fj
  publish-container:
    image: code.cartoon-aa.xyz/ci/plugin-kaniko:2.1.0
    settings:
      repo: ${CI_REPO_OWNER,,}/${CI_REPO_NAME}
      platforms: linux/amd64
      auto_tag: true
      registry: ${CI_FORGE_URL##https://}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: token
  publish-builds:
    image: codeberg.org/forgejo-contrib/forgejo-cli:latest
    pull: true
    environment:
      TOKEN:
        from_secret: token
    commands:
      - export FORGE_HOST=$(echo $CI_FORGE_URL | sed -E 's_^https?://__')
      - fj --host $CI_FORGE_URL auth add-key $CI_REPO_OWNER $TOKEN
      - fj release --repo $CI_REPO_URL asset create $CI_COMMIT_TAG forgejo-cli-x86_64-windows.zip
      - fj release --repo $CI_REPO_URL asset create $CI_COMMIT_TAG forgejo-cli-x86_64-linux.tar.gz
      - fj auth logout $FORGE_HOST

